"""
Compare Munir's commercial and open-weight routes on the SAME golden set.

SECTION 6 — COMMERCIAL VS OPEN-WEIGHT

This script is an evaluation script, not a second application.

It sends the golden cases through build_assistant(route=...) so both
model choices use the real Munir pipeline:

    guards -> router -> handler -> output guard

Default:

    python scripts/compare_models.py --limit 120

The benchmark disables:
- response caching
- FAQ cascade

This makes the comparison fair because both routes must actually
execute their model requests.

IMPORTANT:

The default mock backend is reproducible and is used for the project's
deterministic evaluation. The throughput value used for the
self-host break-even calculation is currently a documented benchmark
assumption rather than a measurement from this environment.

The benchmark assumption is 950 output tokens/second, matching the
throughput value used in the mentor project's break-even methodology.

Replace this value with measured real-provider/open-weight throughput
before using the result as production capacity evidence.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]

# Allow this script to import the Munir application and evaluation package.
sys.path.insert(0, str(ROOT))

from eval.harness import evaluate_assert  # noqa: E402
from munir.domain.session import Session  # noqa: E402
from munir.app import build_assistant  # noqa: E402


# The project's committed golden set.
GOLDEN = ROOT / "eval" / "golden" / "regression_set.yaml"

# Section 6 results are written here.
OUT = ROOT / "eval" / "out"

# These are the slices required for meaningful comparison.
SLICE_KEYS = (
    "language",
    "intent",
    "difficulty",
    "risk",
)

# The two routes we want to compare.
DEFAULT_ROUTES = (
    "primary",
    "open_weight",
)

# ---------------------------------------------------------------------------
# SECTION 6.3 — SELF-HOST BREAK-EVEN THROUGHPUT
# ---------------------------------------------------------------------------
#
# This is a documented benchmark assumption, not a measurement from the
# current environment.
#
# It is used by scripts/breakeven.py to calculate the self-hosted
# cost-per-million-tokens and the utilization level where self-hosting
# becomes cheaper than a hosted commercial model.
#
# The value follows the throughput figure used in the mentor project's
# break-even methodology.
#
# IMPORTANT:
# Replace this value with measured real-provider/open-weight throughput
# before using it as production capacity evidence.
MEASURED_OUTPUT_TOKENS_PER_SECOND = 950.0


def run_route(
    route: str,
    cases: list[dict],
) -> dict:
    """
    Run every selected golden case through one model route.

    The SAME list of cases is supplied to every route.
    """

    # Disable cache and cascade for a fair model comparison.
    #
    # Without this, one route might answer from cache or call
    # an additional model, making the comparison unfair.
    assistant = build_assistant(
        route=route,
        cache_enabled=False,
        cascade_enabled=False,
    )

    results: list[dict] = []

    started = time.perf_counter()

    for case in cases:
        # Use the student ID from the golden case when available.
        student_id = case["vars"].get(
            "student_id",
            f"STU-{case['id']}",
        )

        session = Session(
            student_id=student_id,
        )

        # This is the SAME application entry point used by Munir.
        reply = assistant.ask(
            case["vars"]["student_message"],
            session,
            remember=False,
        )

        failures = []

        # Reuse the exact deterministic assertions from the evaluation
        # harness instead of inventing new Section 6 assertions.
        for spec in case["assert"]:
            passed, detail = evaluate_assert(
                spec,
                reply,
                case,
            )

            if not passed:
                failures.append(
                    {
                        "type": spec["type"],
                        "value": spec.get("value"),
                        "detail": detail,
                    }
                )

        results.append(
            {
                "id": case["id"],
                "strata": case["strata"],
                "passed": not failures,
                "failures": failures,
                "latency_ms": round(
                    reply.latency_ms,
                    1,
                ),
            }
        )

    wall_s = time.perf_counter() - started

    # CostMeter contains the usage records generated by the actual
    # LLM responses.
    records = assistant.meter.records

    output_tokens = sum(
        record.output_tokens
        for record in records
    )

    # Keep the actual observed model time in the report because it is
    # useful diagnostic information. With the deterministic mock backend,
    # this value may be zero or near zero.
    model_time_s = (
        sum(record.latency_ms for record in records)
        / 1000.0
    )

    # Calculate the observed throughput when real latency information
    # is available.
    observed_throughput = (
        output_tokens / model_time_s
        if model_time_s > 0
        else 0.0
    )

    passed = sum(
        1
        for result in results
        if result["passed"]
    )

    # Build pass/fail counts for every evaluation slice.
    slices: dict[
        str,
        dict[str, dict[str, int]],
    ] = {
        key: {}
        for key in SLICE_KEYS
    }

    for result, case in zip(
        results,
        cases,
    ):
        for key in SLICE_KEYS:
            value = case["strata"].get(
                key,
                "?",
            )

            bucket = slices[key].setdefault(
                value,
                {
                    "total": 0,
                    "passed": 0,
                },
            )

            bucket["total"] += 1
            bucket["passed"] += int(
                result["passed"]
            )

    return {
        "route": route,

        "cases": len(cases),

        "passed": passed,

        "pass_rate": round(
            passed / len(cases),
            4,
        )
        if cases
        else 0.0,

        "slices": {
            key: {
                value: round(
                    bucket["passed"]
                    / bucket["total"],
                    4,
                )
                for value, bucket
                in sorted(values.items())
            }
            for key, values in slices.items()
        },

        "slice_counts": {
            key: {
                value: bucket["total"]
                for value, bucket
                in sorted(values.items())
            }
            for key, values in slices.items()
        },

        # Section 5's real cost meter is reused here.
        "cost_sar": assistant.meter.total_sar,

        "model_calls": len(records),

        "input_tokens": sum(
            record.input_tokens
            for record in records
        ),

        "cached_input_tokens": sum(
            record.cached_tokens
            for record in records
        ),

        "output_tokens": output_tokens,

        "wall_s": round(
            wall_s,
            3,
        ),

        "model_time_s": round(
            model_time_s,
            3,
        ),

        # Actual throughput observed during this run.
        "observed_output_tokens_per_second": round(
            observed_throughput,
            2,
        ),

        # Benchmark assumption used by the break-even calculation.
        "measured_output_tokens_per_second": (
            MEASURED_OUTPUT_TOKENS_PER_SECOND
        ),

        "throughput_source": (
            "documented benchmark assumption; "
            "replace with measured real-provider/open-weight "
            "throughput before production use"
        ),

        "results": results,
    }


def print_report(
    reports: list[dict],
) -> None:
    """
    Print a human-readable comparison.

    The JSON file is the machine-readable evidence;
    this output makes the experiment easy to inspect.
    """

    print("\nCOMMERCIAL VS OPEN-WEIGHT")
    print("=" * 78)

    for report in reports:
        print(
            f"{report['route']:<12} "
            f"pass={report['passed']}/{report['cases']} "
            f"({report['pass_rate']:.0%}) | "
            f"cost={report['cost_sar']:.4f} SAR | "
            f"calls={report['model_calls']} | "
            f"benchmark tok/s="
            f"{report['measured_output_tokens_per_second']:.2f}"
        )

        # Print actual observed throughput separately so it is not
        # confused with the documented benchmark assumption.
        print(
            f"  observed tok/s: "
            f"{report['observed_output_tokens_per_second']:.2f}"
        )

        # Print each required comparison slice.
        for key in SLICE_KEYS:
            pieces = [
                f"{value}={rate:.0%}"
                for value, rate in report["slices"][key].items()
            ]

            print(
                f"  {key:<11}: "
                + " | ".join(pieces)
            )

    # If exactly two routes are being compared, calculate the
    # difference for every slice.
    if len(reports) == 2:
        first, second = reports

        print(
            "\nSLICE DELTAS "
            "(second route minus first route)"
        )

        for key in SLICE_KEYS:
            values = sorted(
                set(first["slices"][key])
                | set(second["slices"][key])
            )

            for value in values:
                delta = (
                    second["slices"][key].get(
                        value,
                        0,
                    )
                    - first["slices"][key].get(
                        value,
                        0,
                    )
                )

                print(
                    f"  {key:<11} "
                    f"{value:<12} "
                    f"{delta:+.0%}"
                )


def main() -> int:
    """
    Command-line entry point.
    """

    parser = argparse.ArgumentParser(
        description=(
            "Compare commercial and open-weight "
            "Munir routes on the same golden set."
        )
    )

    parser.add_argument(
        "--routes",
        nargs="+",
        default=list(DEFAULT_ROUTES),
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
    )

    parser.add_argument(
        "--out",
        default=str(
            OUT
            / "commercial_vs_open_weight.json"
        ),
    )

    args = parser.parse_args()

    # Load the project's OWN golden set.
    cases = yaml.safe_load(
        GOLDEN.read_text(
            encoding="utf-8",
        )
    )

    if args.limit:
        cases = cases[: args.limit]

    # Every route receives the exact same ordered cases.
    reports = [
        run_route(
            route,
            cases,
        )
        for route in args.routes
    ]

    payload = {
        "golden_set": str(
            GOLDEN.relative_to(ROOT)
        ),

        "cases": len(cases),

        "routes": reports,

        "method": {
            "cache_enabled": False,
            "faq_cascade_enabled": False,
            "same_assertions": True,
            "same_golden_cases": True,

            "note": (
                "The 950 output-tokens/second throughput value is "
                "a documented benchmark assumption used for the "
                "self-host break-even calculation. It is not a "
                "measurement from the current environment. "
                "Measured real-provider/open-weight throughput should "
                "replace it before production capacity decisions."
            ),
        },
    }

    print_report(reports)

    output = Path(args.out)

    output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    output.write_text(
        json.dumps(
            payload,
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    print(
        f"\nwritten: {output}"
    )

    # This script is a comparison/measurement tool,
    # not the project's regression gate.
    #
    # Section 4's regression gate remains responsible for
    # deciding whether the system is acceptable.
    return 0


if __name__ == "__main__":
    raise SystemExit(main())